name: Lighthouse Audit
on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit livedemo from Vercel
        uses: treosh/lighthouse-ci-action@v12
        with:
          # 這裡填入你部署在 Vercel 的網址
          urls: 'https://2025-12-08-urbnstep-layout-1ocp.vercel.app/' 
          # 讓 Action 上傳報告，這樣你可以看到視覺化圖表
          uploadArtifacts: true 
          # 設定分數門檻，如果低於 90 分，GitHub Action 會顯示失敗 (紅叉)
          # budgetPath: ./lighthouse-budgets.json 
